// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deoaobincsmdvgnkgcac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb2FvYmluY3NtZHZnbmtnY2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDY2MjUsImV4cCI6MjA1OTA4MjYyNX0.z6iX8YLXiN6rJCfUrEamMO2nfKOaWClW66ouhocdTAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);